### ISSUE TITLE
Editable Textarea That Supports Syntax-Highlighted Code

### ISSUE THREAD

**Issue by Harshal141** [ni5arga/DevPad#10]
I am came across this project for hacktober fest.
Was thinking if the textarea in html css and js could have a syntax highlighers in them.
Can i try working on this?

EX: 
![image](https://github.com/ni5arga/DevPad/assets/91362856/44e19e66-3560-44f6-8c00-c14141e8d699)

References: https://css-tricks.com/creating-an-editable-textarea-that-supports-syntax-highlighted-code/

**Comment by ni5arga** [comment]
Yeah you can work on this :)

**Comment by Harshal141** [comment]
I have created a pull request for it.
https://github.com/ni5arga/DevPad/pull/11
